version: '3.1'
volumes:
  db-data:
  sftp-data:
services:
  dbPostgresql:
    image: postgres
    restart: always
    container_name: elevating-db-container
    expose:
      - 5434
    volumes:
      - db-data
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=elevator
    command:
      - -p 5434

  app:
    container_name:  elevating-api
    image: elevating-api:latest
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8092:8092"
    depends_on:
      - dbPostgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbPostgresql:5433/elevating
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
